##########################################
##                                      ##
##      Bungee Chat Filter Config       ##
##               v1                     ##
##########################################

#Monitor commands - Monitor commands send by the players as chat
Monitor Commands: true

#Commands - The list of commands that the plugin will monitor
Commands:
    - msg
    - message
    - tell
    - whisper
    - w
    - g
    - global
    - s
    - l
    - local
    - hub

#AntiSpam - Stop people from reposting the same message multiple times
AntiSpam: true


#Rules - Groups of rules which monitor the chat
#rules:
#   rulename:  - the name of the rule
#       regex:  - the string regex that the rule will check for
#       ignores:  - works in replace and lower, this will ignore any matches that match this regex
#       permission: - the permission required to bypass this rule
#       actions: - here is the list of actions the rule will perform if matched
#           deny: true      - this will deny the message and cancel the event
#           message: (message)      -this will send a message (message) to the player
#           kick: (message)     - this will kick the player with the (message)
#           alert: (message)        - this will send a broadcast to the server {player} will be replaced with the players display name
#           command: /(command)     - this will cause the player to send the (command)
#           remove: true        - this will remove any matches from the players message
#           replace:              - this will replace the matched word with a random word from the list below
#               - word1
#               - word2
#           lower:            - this will change any matches into lowercase

rules:

#Filters the word fuck and replaces it with a random word from the list
    swearfilter1:
        regex: (?i)(f+u+c+k+|f+u+k+|f+v+c+k+|f+u+q+)
        actions:
            replace:
                - fudge
                - frack
                - funk
                - fork

#Filters the list of swear words below and replaces them with a random word from the list. Uses a list as the regex
#The first item has (?i)(cunt to make the generated regex case insensitive.
    swearfilter2:
        regex: (?i)(cunt|whore|fag|slut|queer|bitch|bastard|dick|gay)
            - (?i)(cunt
            - whore
            - fag
            - slut
            - queer
            - bitch
            - bastard
            - dick
            - gay
        actions:
            replace:
                - lovely
                - sweetie
                - sexy

#Filters the word nigger and denys the chat even while kicking the player and alerting the server why the player was kicked
    swearfilter3:
        regex: "n[^a]gg+(a|er|uh)"
        actions:
            deny: true
            alert: "{player} has been kicked for racism"
            kick: "You have been kicked for racism"

#Replaces the word bloodsplat with a coloured word if they have permission for colours and a chat plugin on the server that supports colors.
    colorReplace:
        regex: "bloodsplat"
        actions:
            replace:
                - "&cBloodsplat"
                #Will only work if the player has permission for colors on the servers chat plugin.


#when a player asks for op they will instead say one of the following from the list and be sent a message
    askforOP:
        regex: "(?i).*give me op.*|.*can i have op.*"
        actions:
            replace:
                - Can you please ban me
                - I use xray!
            message: '&cPlease don''t ask for OP'

#When the player uses 4 or more letters in a row all in caps lock then the message will be changed to lowercase
    CAPSPAM:
        regex: (\p{Lu}|\s){4,}
        actions:
            lower: true

#Removes magic, bold and italics from the players chat when they dont have the bungeefilter.antiformatbypass permission.
    AntiFormatText:
        regex: '&[k-o]'
        permission: bungeefilter.antiformatbypass
        actions:
            remove: true
            message: '&cYou do not have permission to use Format text'

#Removes color from the chat unless the player has the bungeefilter.colorbypass permission
    AntiColorText:
        regex: "&[0-9 a-f]"
        permission: bungeefilter.colorbypass
        actions:
            remove: true
            message: '&cYou do not have permission for colors'

#Replaces all ip adresses and web addresses unless it matches the ignore list regex
    AntiAdvertising:
        regex: \b\d{1,3}+\p{P}*\d{1,3}+\p{P}*\d{1,3}+\p{P}*\d{1,3}+\b|([\w-\.]+)((?:[\w]+\.)+)([a-zA-Z]{2,4})
        ignores: minecraft.net|youtube.com|google.com
        actions:
            replace:
                - minecraft.net
            message: '&cPlease do not advertise on our server'

#When a player uses the command /hub they will instead cast the command /server hub to the proxy. Denies the command so /hub isnt also sent
    CommandShortcut:
        regex: /hub
        actions:
            pcommand: /server hub
            deny: true

#When a player uses the command /shop they will instead send a command to the server they are on /warp shop.
    CommandShortcut2:
        regex: /shop
        actions:
            scommand: /warp shop
            deny: true

#Creates a proxywide broadcast command !bungeefilter.broadcast means the player needs the permission for the check to work
    CreateCommand:
        regex: /broadcast
        permission: "!bungeefilter.broadcast"
        actions:
            alert: '&5[Broadcast]&a{player}&f:{arguments}'
            deny: true